### PR TITLE
BUGFIX: Cast flash message to string

### LINKED ISSUE #50: BUG: addFlashMessage can not handle Message object
When purging content cache for a certain content type (ex. text/css) you will get the following exception after the purging is done

Exception #1243258395 in line 175 of /var/www/website/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/MOC_Varnish_Controller_VarnishCacheController.php: The message body must be of type string, "object" given. - See also: 20200513062504a2ac87.txt

This is due to a Object being passed to the flashMessage.

This change cast it to a string (using the __toString) method of the Message object

### PR DESCRIPTION
**Pull request by sorenmalling**
When purging content cache for a certain content type (ex. text/css) you will get the following exception after the purging is done

Exception #1243258395 in line 175 of /var/www/website/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/MOC_Varnish_Controller_VarnishCacheController.php: The message body must be of type string, "object" given. - See also: 20200513062504a2ac87.txt

This is due to a Object being passed to the flashMessage.

This change cast it to a string (using the __toString) method of the Message object

Resolves: #50

### CODE REVIEW

File: Classes/Controller/VarnishCacheController.php [hunk 1]
```diff
@@ -172,7 +172,7 @@ public function purgeAllVarnishCacheAction(Site $site = null, $contentType = nul
         }
         $service = new VarnishBanService();
         $service->banAll($domains, $contentType);
-        $this->addFlashMessage(new Message(sprintf('All varnish cache cleared for %s%s', $site ? 'site ' . $site->getName() : 'installation', $contentType ? ' with content type "' . $contentType . '"' : '')));
+        $this->addFlashMessage((string) new Message(sprintf('All varnish cache cleared for %s%s', $site ? 'site ' . $site->getName() : 'installation', $contentType ? ' with content type "' . $contentType . '"' : '')));
```
Comment (paxuclus) [inline Classes/Controller/VarnishCacheController.php]: I'd suggest to drop the `new Message()` completely so it's just a sprintf like the other flashmessage in `purgeCacheByTagsAction()`.

**Review by paxuclus — CHANGES_REQUESTED** [review]
Thanks for the PR @sorenmalling. Could you please fix my tiny nitpick? :)

File: Classes/Controller/VarnishCacheController.php (hunk 1 above)
Comment (sorenmalling) [reply Classes/Controller/VarnishCacheController.php]: You got it :-)

**Review by paxuclus — APPROVED** [review]
